name: Generate PDF

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Latex Requirements
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-xetex texlive texlive-fonts-recommended texlive-fonts-extra poppler-utils

      - name: Generate pdf
        run: | 
          xelatex -8bit -halt-on-error resume.tex
          mv resume.pdf Josiah_Bull-Resume.pdf
          
      - name: Generate image
        run: |
          pdftoppm -png Josiah_Bull-Resume.pdf Josiah_Bull-Resume
          mv Josiah_Bull-Resume-1.png Josiah_Bull-Resume.png

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: |
            Josiah_Bull-Resume.pdf
            Josiah_Bull-Resume.png
